version: "3"
services:
  mysite:
    build:
      context: ./
    ports:
      - 9000:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DEBUG: "True"

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: polls
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
    - mysql_data:/va/lib/mysql/
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

volumes:
  mysql_data:
